config:
  client_id: <ClientID from Azure SPN>
  client_secret: <Client Secret from Azure SPN>,
  authority: https://login.microsoftonline.com/<AZURE TENANT ID>,
  scope: ['https://graph.microsoft.com/.default']


dbx_config: 
  dbx_host: <Databricks Workspace URL>
  dbx_account_host: 'https://accounts.azuredatabricks.net'
  account_id: <Databricks AccountID>
  azure_tenant_id: <Azure Tenant ID>
  client_id: <Client ID for azure SPN>
  client_secret: <Client Secret for azure SPN>

LOG_FILE_LOCATION: '/Users/bimal.sebastian/SourceCode/tmp/'
LOG_FILE_NAME : log

groups_to_sync_path : 'groups_to_sync.json'

is_dryrun: True


deactivate_deleted_users : True